let g:ackprg = 'ag --nogroup --nocolor --column'

" Número de linhas
set number
set mouse=a     
"  Cor de sintaxe

set ai
set hlsearch
set ruler
highlight Comment ctermfg=green

" Correção de tabs
set tabstop=2
set shiftwidth=2
set expandtab
set softtabstop=2
set autoindent 
set smartindent 
set nocompatible   
syntax on

filetype off                  " required
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'preservim/nerdtree'
Plugin 'hail2u/vim-css3-syntax'
Plugin 'mxw/vim-jsx'
Plugin 'millermedeiros/vim-esformatter'
Plugin 'jiangmiao/auto-pairs'
Plugin 'HTML-AutoCloseTag'
Plugin 'othree/html5.vim'
Plugin 'jelera/vim-javascript-syntax'
Plugin 'tmux-plugins/vim-tmux'
Plugin 'jonathanfilip/vim-lucius'

call vundle#end()            
filetype plugin indent on  

let g:user_emmet_leader_key=','
let g:togglecursor_disable_tmux = 1

colorscheme koehler

augroup RestoreCursorShapeOnExit
  autocmd!
  autocmd VimLeave * set guicursor+=a:ver1-Cursor/lCursor
augroup END

let &t_SI = "\<Esc>]50;CursorShape=1\x7"
let &t_SR = "\<Esc>]50;CursorShape=2\x7"
let &t_EI = "\<Esc>]50;CursorShape=0\x7"

set ttimeout
set ttimeoutlen=1
set listchars=tab:>-,trail:~,extends:>,precedes:<,space:.
set ttyfast
