let g:ackprg = 'ag --nogroup --nocolor --column'

" Número de linhas
set number
set mouse=a     
"  Cor de sintaxe

set ai
set hlsearch
set ruler
highlight Comment ctermfg=green

" Correção de tabs
set tabstop=2
set shiftwidth=2
set expandtab
set softtabstop=2
set autoindent 
set smartindent 
set nocompatible   
syntax on

colorscheme koehler

filetype off                  " required
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'preservim/nerdtree'
Plugin 'hail2u/vim-css3-syntax'
Plugin 'mxw/vim-jsx'
Plugin 'millermedeiros/vim-esformatter'
Plugin 'jiangmiao/auto-pairs'
Plugin 'HTML-AutoCloseTag'
Plugin 'othree/html5.vim'
Plugin 'jelera/vim-javascript-syntax'
Plugin 'tmux-plugins/vim-tmux'

call vundle#end()            
filetype plugin indent on  

